name: Check on Rust stable

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  check-stable:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            features: --features jack

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools and dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y libasound2-dev libjack-dev

      - name: Install Rust stable
        run: rustup toolchain install stable --profile minimal

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Compile on ${{ matrix.os }} with Rust stable
        run: |
          cargo check --verbose ${{ matrix.features || '' }}
